name: terrestraClient
version: 0.0.1
author: Klaus Wörner & Peter Holmeier
description: Client for Terrestra
homepage: http://github.com/terrestra/terrestra
dependencies:
  browser: any
  simple_audio:
    git: https://github.com/johnmccutchan/simpleaudio.git
